/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TwdsHexagram {
        "lines": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTwdsHexagramElement extends Components.TwdsHexagram, HTMLStencilElement {
    }
    var HTMLTwdsHexagramElement: {
        prototype: HTMLTwdsHexagramElement;
        new (): HTMLTwdsHexagramElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "twds-hexagram": HTMLTwdsHexagramElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TwdsHexagram {
        "lines"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "twds-hexagram": TwdsHexagram;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "twds-hexagram": LocalJSX.TwdsHexagram & JSXBase.HTMLAttributes<HTMLTwdsHexagramElement>;
        }
    }
}
